# Generated by Django 4.2.3 on 2023-08-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grocery_run", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="bought",
            field=models.BooleanField(default=False),
        ),
    ]
