# Generated by Django 4.2.3 on 2023-08-07 22:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grocery_run", "0002_item_bought"),
        ("grocery_run", "0003_item_user"),
    ]

    operations = []
