# Generated by Django 4.2.3 on 2023-08-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grocery_run", "0004_merge_0002_item_bought_0003_item_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="store_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="store",
                to="grocery_run.store",
            ),
        ),
    ]
